/* Generated By:JJTree: Do not edit this line. ASTCondition.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package it.unisannio.paradigmi;

public
class ASTCondition extends SimpleNode {
  public ASTCondition(int id) {
    super(id);
  }

  public ASTCondition(Tiny p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0501b2093028435917ec624f71cfc131 (do not edit this line) */
