/* Generated By:JJTree: Do not edit this line. ASTCallWrite.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package it.unisannio.paradigmi;

public
class ASTCallWrite extends SimpleNode {
  public ASTCallWrite(int id) {
    super(id);
  }

  public ASTCallWrite(Tiny p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cc506ab913d1660c57290368d509571e (do not edit this line) */
