/* Generated By:JJTree: Do not edit this line. ASTCallRead.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package it.unisannio.paradigmi;

public
class ASTCallRead extends SimpleNode {
  public ASTCallRead(int id) {
    super(id);
  }

  public ASTCallRead(Tiny p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a73cfb5103b114b13d66c00cb107db59 (do not edit this line) */
