/* Generated By:JJTree: Do not edit this line. ASTIfThen.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package it.unisannio.paradigmi;

public
class ASTIfThen extends SimpleNode {
  public ASTIfThen(int id) {
    super(id);
  }

  public ASTIfThen(Tiny p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0212a1db554b6886930579010da2863f (do not edit this line) */
