/* Generated By:JJTree: Do not edit this line. ASTMulDivExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package it.unisannio.paradigmi;

public
class ASTMulDivExpr extends SimpleNode {
  public ASTMulDivExpr(int id) {
    super(id);
  }

  public ASTMulDivExpr(Tiny p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d64d90327b1293bfcac0013396bbc6a2 (do not edit this line) */
