/* Generated By:JJTree: Do not edit this line. ASTProgram.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package it.unisannio.paradigmi;

public
class ASTProgram extends SimpleNode {
  public ASTProgram(int id) {
    super(id);
  }

  public ASTProgram(Tiny p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=37e05a2df0c1c2cfcad4955ee301ce4c (do not edit this line) */
