/* Generated By:JJTree&JavaCC: Do not edit this line. TinyConstants.java */
package it.unisannio.paradigmi;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int END = 1;
  /** RegularExpression Id. */
  int READFNC = 2;
  /** RegularExpression Id. */
  int WRITEFNC = 3;
  /** RegularExpression Id. */
  int SEMICOLON = 4;
  /** RegularExpression Id. */
  int THEN = 5;
  /** RegularExpression Id. */
  int IF = 6;
  /** RegularExpression Id. */
  int REPEAT = 7;
  /** RegularExpression Id. */
  int UNTIL = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int NUMBER = 10;
  /** RegularExpression Id. */
  int ID = 11;
  /** RegularExpression Id. */
  int ASSIGMENT = 12;
  /** RegularExpression Id. */
  int LEF_BRA = 13;
  /** RegularExpression Id. */
  int RIGHT_BRA = 14;
  /** RegularExpression Id. */
  int MULT_DIV = 15;
  /** RegularExpression Id. */
  int SUM_DIF = 16;
  /** RegularExpression Id. */
  int COMPARISON = 17;
  /** RegularExpression Id. */
  int NUMBA = 18;
  /** RegularExpression Id. */
  int LETTER = 19;
  /** RegularExpression Id. */
  int SKIPPED = 20;
  /** RegularExpression Id. */
  int COMMENT = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"end\"",
    "\"read\"",
    "\"write\"",
    "\";\"",
    "\"then\"",
    "\"if\"",
    "\"repeat\"",
    "\"until\"",
    "\"else\"",
    "<NUMBER>",
    "<ID>",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "<MULT_DIV>",
    "<SUM_DIF>",
    "<COMPARISON>",
    "<NUMBA>",
    "<LETTER>",
    "<SKIPPED>",
    "<COMMENT>",
  };

}
