options {
    STATIC = false;
    MULTI = true;
    NODE_DEFAULT_VOID = true;
    BUILD_PARSER = true;
    BUILD_NODE_FILES = true;
}

PARSER_BEGIN(Tiny)

package it.unisannio.paradigmi;
import it.unisannio.symbolTable.*;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.FileNotFoundException;

public class Tiny {
  
  final private int SKIP_ONE = -1;
  final private int SKIP_TWO = -2;

    public static void main(String[] args) throws ParseException, FileNotFoundException {

      

        InputStream s;
        if (args.length > 0) {
            s = new FileInputStream(args[0]);
        } else {
            s = System.in;
        }

        Tiny t = new Tiny(s);
        SimpleNode n = t.Program();
        printTree(n,"",true);
        
    }


      public static void printTree(SimpleNode node, String prefix, boolean isTail) { 
		String GREEN = "\u001B[32m";       
		String RESET = "\u001B[0m";
		
		if (node == null) {
            return;
        }

        // Stampa il nodo corrente
        System.out.print(prefix);
        System.out.print(isTail ? "└── " : "├── ");
        if(node.value != null)
        System.out.println(node.toString()+ ": "+ GREEN + node.value +RESET); 
		else
		System.out.println(node.toString());
		
        // Costruisci il nuovo prefisso per i figli
        prefix += isTail ? "    " : "│   ";

        // Visita i figli del nodo
        for (int i = 0; i < node.jjtGetNumChildren(); i++) {
            SimpleNode child = (SimpleNode) node.jjtGetChild(i);
            printTree(child, prefix, i == node.jjtGetNumChildren() - 1);
        }
    }

    
			    
}

PARSER_END(Tiny)

// Dichiarazioni del gestore di token
TOKEN_MGR_DECLS : {
  	
    int KEYS = 0;
    int CONTROLS = 0;
    int COMMENTS = 0;
    SymbolTable symbolTable = new SymbolTable();
}

// Definizione dei token
TOKEN : {
    <END: "end">                                 { KEYS++; }
  | <READFNC: "read">                           { KEYS++; }
  | <WRITEFNC: "write">                         { KEYS++; }
  | <SEMICOLON: ";">                            { KEYS++; }
  | <THEN: "then">                              { KEYS++; }
  | <IF: "if">                                  { KEYS++; CONTROLS++; }
  | <REPEAT: "repeat">                          { KEYS++; CONTROLS++; }
  | <UNTIL: "until">                            { KEYS++; }
  | <ELSE: "else">
}

TOKEN : {
  <NUMBER: (<NUMBA>)+>                          { KEYS++; }
  | <ID: <LETTER>(<LETTER> | <NUMBA> | "_" )*>  { KEYS++; symbolTable.put(matchedToken.image, matchedToken.kind, matchedToken.beginLine, matchedToken.endLine, matchedToken.beginColumn, matchedToken.endColumn); }
}

TOKEN : {
   <ASSIGNMENT: ":=">                            { KEYS++; }
  | <LEF_BRA: "(">
  | <RIGHT_BRA: ")">
  | <MULT_DIV: ("/"|"*")>                       { KEYS++; }
  | <SUM_DIF: ("-"|"+")>                        { KEYS++; }
  | <COMPARISON: ("<"|"="|">")>                 { KEYS++; }
  | < NEWLINE: "\n" >                           { KEYS++; }
}

TOKEN : {
  <#NUMBA: (["0"-"9"])>
  | <#LETTER: (["A"-"Z","a"-"z"])>
}

SKIP : {
    < SKIPPED : [" ", "\t", "\r"]>
   | <COMMENT: "{" (~["}"])* "}" > { COMMENTS++; }
}


//  error management methods --------------------------

JAVACODE // this function recovers form error in panic mode fashion, by skipping tokens until a synchronization point is found
		// with SKIP_ONE it skips only one token
void error_skip(int kind) {
	ParseException e = generateParseException();
	Token t = new Token();
	boolean first = true;
	int next = 0;
	int	  startC = 0;
	int  startL = 0;
			while (true){
				next++;
				// make the token advance without moving the pointer
				t = getToken(next);
	            Token advancing = new Token();
	            if(first) { 
				startC = t.beginColumn;
				startL = t.beginLine;
				first = false;
		        }
				// once a synchronization point is found make the pointer advance
				if(kind == SKIP_TWO || kind == SKIP_ONE || t.kind == kind || t.kind == NEWLINE || t.kind == EOF) {
					if (kind == SKIP_TWO) {
					  next ++;
					  next ++;
					  
					  }


	                for (int i = 0; i < next-1; i++) {
	                  advancing = getNextToken();
	                  }
	                  

					if(kind != SKIP_TWO) System.err.println(e.toString());
					System.err.println("ERROR RECOVERED with panic mode");
					System.err.println("ignoring from: Column - "  + startC + " Row - " + startL  + "\nto: Column - " +  t.beginColumn + " Row - " + t.beginLine + "\n");
					return;
				}
		}
}


				
	           

JAVACODE
void general_error() {
        ParseException e = generateParseException();

        if(e.toString().contains("until")) {
          System.err.println("ERROR: until statement out of repeat context at line " + (token.beginLine + 1));

          } else if (e.toString().contains("end")) {
			System.err.println("ERROR: end statement out of if-then context at line " + (token.beginLine + 1));

			} else {
            System.err.println("ERROR: general error at line: " + token.beginLine);
          }
          
    }

JAVACODE
void control_flow_with_semicolon() {
        System.err.println("\nERROR: control statements must not be followed by semicolon line: " + token.beginLine); error_skip(NEWLINE); 
    }


JAVACODE
void condition_error() {
		System.err.println("bad formatted condition at row: " + token.beginLine );
	}
// -----------------------------	




// Definizione delle regole sintattiche con nodi per l'AST
SimpleNode Program() #Program : {}
{
 try { 
   (< NEWLINE >)* Statements() <EOF>
    { return jjtThis; }
    } catch (ParseException e) {
      general_error();
      error_skip(NEWLINE);
      return jjtThis;
    }
 
}


void Statements() #Statements : {}
{
    Statement()  [Statements()]
}

void Statement() #Statement : {}
{

   (CallRead() | CallWrite() | Assignment() | RepeatUntil() | IfThen()) (<NEWLINE>)*

}

void CallRead() #CallRead : {}
{
    <READFNC> <ID> <SEMICOLON>
}

void CallWrite() #CallWrite : {}
{
    <WRITEFNC> (<ID>|<NUMBER>) <SEMICOLON> 
}

void Assignment() #Assignment : {}
{
  try {
    <ID> <ASSIGNMENT> Expression() try { <SEMICOLON> } catch (ParseException e) {
      System.err.println("ERROR: missing semicolon at line: " + token.beginLine);
      error_skip(NEWLINE);
    }
	   } catch (ParseException e) {
		   System.err.println("ERROR: missing assignment symbol at line: " + token.beginLine + " column: " + token.beginColumn);
	  		error_skip(NEWLINE);
	  	}
}

void Expression() #Expression : {}
{
	MulDivExpr() ExpressionExt() 
}

void ExpressionExt() #ExpressionExt : { }
{
  [sumDif() MulDivExpr() ExpressionExt()]
}

void Condition() #Condition : {}
{
    try { Expression() < COMPARISON > Expression() } catch (ParseException e) { condition_error(); error_skip(THEN); }
}


void MulDivExpr() #MulDivExpr : {}
{
    Factor() MulDivExprExt()
}

void MulDivExprExt() #MulDivExprExt : {}
{
  < MULT_DIV > Factor() MulDivExprExt() | { }
}

void Factor() #Factor : {boolean neg = false;}
{
	< ID > { jjtn000.value = token.image;} | <NUMBER> { jjtn000.value = token.image;}  | <LEF_BRA> Expression() <RIGHT_BRA> | <SUM_DIF><NUMBER> { jjtn000.value = "-" +  token.image; neg = false; } 
}

void IfThen() #IfThen : {}
{

 <IF> Condition() try { <THEN> } catch (ParseException e) {
   System.err.println("ERROR IGNORED: missing then statement at line: " + token.beginLine + " column: " + token.beginColumn );
   System.err.println(e.toString());
	} try {  <NEWLINE> } catch (ParseException e) {control_flow_with_semicolon();} Statements() [<ELSE> Statements()]  <END> <NEWLINE>                       

}

void RepeatUntil() #RepeatUntil : {int S = token.beginLine + 1;}
{
    <REPEAT> try { <NEWLINE> } catch(ParseException e) { control_flow_with_semicolon();} Statements() try { < UNTIL >  } catch (ParseException e) {
    System.err.println("\nERROR missing until statement for repeat at line: " + S);
    error_skip(NEWLINE);
    return;
	
    } Condition()  try {  <NEWLINE> } catch (ParseException e) {control_flow_with_semicolon();}
}



void sumDif() #sumDif: { }
{
  < SUM_DIF > { jjtn000.value = token.image;}
}


