/* Generated By:JavaCC: Do not edit this line. TinyTreeConstants.java Version 7.0.12 */
package it.unisannio.paradigmi;

public interface TinyTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENTS = 1;
  public int JJTSTATEMENT = 2;
  public int JJTCALLREAD = 3;
  public int JJTCALLWRITE = 4;
  public int JJTASSIGNMENT = 5;
  public int JJTEXPRESSION = 6;
  public int JJTCONDITION = 7;
  public int JJTMULDIVEXPR = 8;
  public int JJTFACTOR = 9;
  public int JJTIFTHEN = 10;
  public int JJTREPEATUNTIL = 11;
  public int JJTID_SYMBOL = 12;
  public int JJTTHEN_SYMBOL = 13;
  public int JJTCOMPARE_SYMBOL = 14;
  public int JJTMULDIV_SYMBOL = 15;
  public int JJTSUMDIF_SYMBOL = 16;


  public String[] jjtNodeName = {
    "Program",
    "Statements",
    "Statement",
    "CallRead",
    "CallWrite",
    "Assignment",
    "Expression",
    "Condition",
    "MulDivExpr",
    "Factor",
    "IfThen",
    "RepeatUntil",
    "ID_SYMBOL",
    "THEN_SYMBOL",
    "COMPARE_SYMBOL",
    "MULDIV_SYMBOL",
    "SUMDIF_SYMBOL",
  };
}
/* JavaCC - OriginalChecksum=7086c65a122c18a229c4ed65a8e1f81f (do not edit this line) */
