/* Generated By:JavaCC: Do not edit this line. TinyTreeConstants.java Version 7.0.12 */
package it.unisannio.paradigmi;

public interface TinyTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENTS = 1;
  public int JJTSTATEMENT = 2;
  public int JJTCALLREAD = 3;
  public int JJTCALLWRITE = 4;
  public int JJTASSIGNMENT = 5;
  public int JJTEXPRESSION = 6;
  public int JJTCONDITION = 7;
  public int JJTMULDIVEXPR = 8;
  public int JJTFACTOR = 9;
  public int JJTIFTHEN = 10;
  public int JJTREPEATUNTIL = 11;


  public String[] jjtNodeName = {
    "Program",
    "Statements",
    "Statement",
    "CallRead",
    "CallWrite",
    "Assignment",
    "Expression",
    "Condition",
    "MulDivExpr",
    "Factor",
    "IfThen",
    "RepeatUntil",
  };
}
/* JavaCC - OriginalChecksum=b50127714a23fd976223ebd8c169cfac (do not edit this line) */
