/* Generated By:JavaCC: Do not edit this line. TinyTreeConstants.java Version 7.0.12 */
package it.unisannio.paradigmi;

public interface TinyTreeConstants
{
  public int JJTVOID = 0;
  public int JJTPROGRAM = 1;
  public int JJTSTATEMENTS = 2;
  public int JJTSTATEMENT = 3;
  public int JJTCALLREAD = 4;
  public int JJTCALLWRITE = 5;
  public int JJTASSIGNMENT = 6;
  public int JJTEXPRESSION = 7;
  public int JJTEXPRESSIONEXT = 8;
  public int JJTCONDITION = 9;
  public int JJTMULDIVEXPR = 10;
  public int JJTMULDIVEXPREXT = 11;
  public int JJTFACTOR = 12;
  public int JJTIFTHEN = 13;
  public int JJTREPEATUNTIL = 14;
  public int JJTSUMDIF = 15;


  public String[] jjtNodeName = {
    "void",
    "Program",
    "Statements",
    "Statement",
    "CallRead",
    "CallWrite",
    "Assignment",
    "Expression",
    "ExpressionExt",
    "Condition",
    "MulDivExpr",
    "MulDivExprExt",
    "Factor",
    "IfThen",
    "RepeatUntil",
    "sumDif",
  };
}
/* JavaCC - OriginalChecksum=eb0fa3d4a7d297e2f1211b6381c619c0 (do not edit this line) */
