options {
    STATIC = false;
    MULTI = true;
    NODE_DEFAULT_VOID = true;
    BUILD_PARSER = true;
    BUILD_NODE_FILES = true;
}

PARSER_BEGIN(Tiny)

package it.unisannio.paradigmi;
import it.unisannio.symbolTable.*;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.FileNotFoundException;

public class Tiny {
    public static void main(String[] args) throws ParseException, FileNotFoundException {

      

        InputStream s;
        if (args.length > 0) {
            s = new FileInputStream(args[0]);
        } else {
            s = System.in;
        }

        Tiny t = new Tiny(s);
        SimpleNode n = t.Program();
		System.out.println("Normally we read AST from left to right. In this representation we go from up to bottom \n\n");
        printTree(n,"",true);
        
    }


      public static void printTree(SimpleNode node, String prefix, boolean isTail) { 
		String GREEN = "\u001B[32m";       
		String RESET = "\u001B[0m";
		
		if (node == null) {
            return;
        }

        // Stampa il nodo corrente
        System.out.print(prefix);
        System.out.print(isTail ? "└── " : "├── ");
        if(node.value != null)
        System.out.println(node.toString()+ ": "+ GREEN + node.value +RESET); 
		else
		System.out.println(node.toString());
		
        // Costruisci il nuovo prefisso per i figli
        prefix += isTail ? "    " : "│   ";

        // Visita i figli del nodo
        for (int i = 0; i < node.jjtGetNumChildren(); i++) {
            SimpleNode child = (SimpleNode) node.jjtGetChild(i);
            printTree(child, prefix, i == node.jjtGetNumChildren() - 1);
        }
    }
    
}

PARSER_END(Tiny)

// Dichiarazioni del gestore di token
TOKEN_MGR_DECLS : {
    int KEYS = 0;
    int CONTROLS = 0;
    int COMMENTS = 0;
    SymbolTable symbolTable = new SymbolTable();
}

// Definizione dei token
TOKEN : {
    <END: "end">                                 { KEYS++; }
  | <READFNC: "read">                           { KEYS++; }
  | <WRITEFNC: "write">                         { KEYS++; }
  | <SEMICOLON: ";">                            { KEYS++; }
  | <THEN: "then">                              { KEYS++; }
  | <IF: "if">                                  { KEYS++; CONTROLS++; }
  | <REPEAT: "repeat">                          { KEYS++; CONTROLS++; }
  | <UNTIL: "until">                            { KEYS++; }
  | <ELSE: "else">
}

TOKEN : {
  <NUMBER: (<NUMBA>)+>                          { KEYS++; }
  | <ID: <LETTER>(<LETTER> | <NUMBA> | "_" )*>  { KEYS++; symbolTable.put(matchedToken.image, matchedToken.kind, matchedToken.beginLine, matchedToken.endLine, matchedToken.beginColumn, matchedToken.endColumn); }
}

TOKEN : {
   <ASSIGMENT: ":=">                            { KEYS++; }
  | <LEF_BRA: "(">
  | <RIGHT_BRA: ")">
  | <MULT_DIV: ("/"|"*")>                       { KEYS++; }
  | <SUM_DIF: ("-"|"+")>                        { KEYS++; }
  | <COMPARISON: ("<"|"="|">")>                 { KEYS++; }
}

TOKEN : {
  <#NUMBA: (["0"-"9"])>
  | <#LETTER: (["A"-"Z","a"-"z"])>
}

SKIP : {
    < SKIPPED : [" ", "\t", "\n", "\r"] >
   | <COMMENT: "{" (~["}"])* "}" > { COMMENTS++; }
}

// Definizione delle regole sintattiche con nodi per l'AST
SimpleNode Program() #Program : {}
{
    Statements() <EOF>
    { return jjtThis; }
}

void Statements() #Statements : {}
{
    Statement()  [Statements()]
}

void Statement() #Statement : {}
{
    CallRead() | CallWrite() | Assignment() | RepeatUntil() | IfThen()
}

void CallRead() #CallRead : {}
{
    <READFNC> <ID> <SEMICOLON>
}

void CallWrite() #CallWrite : {}
{
    <WRITEFNC> (<ID>|<NUMBER>) < SEMICOLON>
}

void Assignment() #Assignment : {}
{
    <ID> <ASSIGMENT> Expression() < SEMICOLON>   
}

void Expression() #Expression : {}
{
	MulDivExpr() (< SUM_DIF > { jjtn000.value = token.image;} MulDivExpr())*
}

void Condition() #Condition : {}
{
    Expression() < COMPARISON > Expression()
}

void MulDivExpr() #MulDivExpr : {}
{
    Factor() (< MULT_DIV > { jjtn000.value = token.image;} Factor())* 
}

void Factor() #Factor : { }
{
     < ID > { jjtn000.value = token.image;} | [<SUM_DIF >] <NUMBER> { jjtn000.value = token.image;} | <LEF_BRA> Expression() <RIGHT_BRA>

}

void IfThen() #IfThen : {}
{
    <IF> Condition() < THEN > Statements() [<ELSE> Statements()] <END>
}

void RepeatUntil() #RepeatUntil : {}
{
    <REPEAT> Statements() <UNTIL> Condition()
}



