/* Generated By:JJTree: Do not edit this line. ASTCallPrint.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package esercizio1;

public
class ASTCallPrint extends SimpleNode {
  public ASTCallPrint(int id) {
    super(id);
  }

  public ASTCallPrint(Tiny p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b64b5b70e21ecb7c2e65aa14655033a0 (do not edit this line) */
