/* Generated By:JJTree: Do not edit this line. ASTdeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package esercizio1;

public
class ASTdeclaration extends SimpleNode {
  public ASTdeclaration(int id) {
    super(id);
  }

  public ASTdeclaration(Tiny p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4a3270f1851c90e0eb43ab4cc5e0b363 (do not edit this line) */
