/* Generated By:JJTree: Do not edit this line. ASTdeclartionExt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package esercizio1;

public
class ASTdeclartionExt extends SimpleNode {
  public ASTdeclartionExt(int id) {
    super(id);
  }

  public ASTdeclartionExt(Tiny p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=36dbcec658d3531c86853a5dbf0aeb75 (do not edit this line) */
