/* Generated By:JJTree: Do not edit this line. ASTExpressionExt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package esercizio1;

public
class ASTExpressionExt extends SimpleNode {
  public ASTExpressionExt(int id) {
    super(id);
  }

  public ASTExpressionExt(Tiny p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ba5092d1a57e61352d03e54464b39fc0 (do not edit this line) */
