/* Generated By:JJTree: Do not edit this line. ASTFactor.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package esercizio1;

public
class ASTFactor extends SimpleNode {
  public ASTFactor(int id) {
    super(id);
  }

  public ASTFactor(Tiny p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=09bf0378b0dfa8f24bf8110b58fd067d (do not edit this line) */
