/* Generated By:JJTree: Do not edit this line. ASTMulDivExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package esercizio1;

public
class ASTMulDivExpr extends SimpleNode {
  public ASTMulDivExpr(int id) {
    super(id);
  }

  public ASTMulDivExpr(Tiny p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cc16a742e636d64ec44f9b453a6b28dd (do not edit this line) */
