/* Generated By:JJTree: Do not edit this line. ASTmultiDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package esercizio1;

public
class ASTmultiDeclaration extends SimpleNode {
  public ASTmultiDeclaration(int id) {
    super(id);
  }

  public ASTmultiDeclaration(Tiny p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6a987647621b92409220c3314528c6c0 (do not edit this line) */
