/* Generated By:JJTree: Do not edit this line. ASTMulDivExprExt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package esercizio1;

public
class ASTMulDivExprExt extends SimpleNode {
  public ASTMulDivExprExt(int id) {
    super(id);
  }

  public ASTMulDivExprExt(Tiny p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=28f05ceab80665b63ea3c511dfe4195b (do not edit this line) */
