/* Generated By:JJTree: Do not edit this line. ASTStatements.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package esercizio1;

public
class ASTStatements extends SimpleNode {
  public ASTStatements(int id) {
    super(id);
  }

  public ASTStatements(Tiny p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6c08b2915a0904740366c0902b916356 (do not edit this line) */
