/* Generated By:JJTree: Do not edit this line. ASTsumDif.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package esercizio1;

public
class ASTsumDif extends SimpleNode {
  public ASTsumDif(int id) {
    super(id);
  }

  public ASTsumDif(Tiny p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=048baaa046433f502f7603d81ea6e508 (do not edit this line) */
