/* Generated By:JJTree&JavaCC: Do not edit this line. TinyConstants.java */
package esercizio1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TYPE = 1;
  /** RegularExpression Id. */
  int PRINTFNC = 2;
  /** RegularExpression Id. */
  int SEMICOLON = 3;
  /** RegularExpression Id. */
  int REPEAT = 4;
  /** RegularExpression Id. */
  int COMMA = 5;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int ID = 7;
  /** RegularExpression Id. */
  int ASSIGNMENT = 8;
  /** RegularExpression Id. */
  int LEF_BRA = 9;
  /** RegularExpression Id. */
  int RIGHT_BRA = 10;
  /** RegularExpression Id. */
  int MULT_DIV = 11;
  /** RegularExpression Id. */
  int SUM_DIF = 12;
  /** RegularExpression Id. */
  int COMPARISON = 13;
  /** RegularExpression Id. */
  int NUMBA = 14;
  /** RegularExpression Id. */
  int LETTER = 15;
  /** RegularExpression Id. */
  int SKIPPED = 16;
  /** RegularExpression Id. */
  int COMMENT = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<TYPE>",
    "\"print\"",
    "\";\"",
    "\"repeat\"",
    "\",\"",
    "<NUMBER>",
    "<ID>",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "<MULT_DIV>",
    "<SUM_DIF>",
    "<COMPARISON>",
    "<NUMBA>",
    "<LETTER>",
    "<SKIPPED>",
    "<COMMENT>",
  };

}
