/* Generated By:JavaCC: Do not edit this line. TinyTreeConstants.java Version 7.0.12 */
package esercizio1;

public interface TinyTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENTS = 1;
  public int JJTSTATEMENT = 2;
  public int JJTCALLPRINT = 3;
  public int JJTDECLARATION = 4;
  public int JJTMULTIDECLARATION = 5;
  public int JJTASSIGNMENT = 6;
  public int JJTEXPRESSION = 7;
  public int JJTEXPRESSIONEXT = 8;
  public int JJTMULDIVEXPR = 9;
  public int JJTMULDIVEXPREXT = 10;
  public int JJTFACTOR = 11;
  public int JJTSUMDIF = 12;
  public int JJTVOID = 13;


  public String[] jjtNodeName = {
    "Program",
    "Statements",
    "Statement",
    "CallPrint",
    "declaration",
    "multiDeclaration",
    "Assignment",
    "Expression",
    "ExpressionExt",
    "MulDivExpr",
    "MulDivExprExt",
    "Factor",
    "sumDif",
    "void",
  };
}
/* JavaCC - OriginalChecksum=eb53f1af20bb7b882a51006cb60d46e2 (do not edit this line) */
